version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      # add any other environment variables your backend might need
    volumes:
      - ./backend:/app  # optional: for live code changes to reflect in the container
